name: aokvqa
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=11.3
  - numpy=1.21.6
  - pytorch=1.11.0
  - torchvision=0.12.0
  - pytorch-lightning=1.6.3
  - torchmetrics=0.8.1
  - gdown=4.4.0
  - pip=22.0.4
  - pip:
    - argparse==1.4.0
    - Pillow==9.0.1
    - tensorboard==2.9.0
    - ftfy==6.1.1
    - regex==2022.3.15
    - tqdm==4.64.0
    - clip @ git+https://github.com/openai/CLIP.git@b46f5ac7587d2e1862f8b7b1573179d80dcdd620
    - openai==0.18.1
    - nltk==3.7
    - sacrebleu==2.0.0
    - sacremoses==0.0.53
    - sentence-transformers==2.2.0
    - datasets==2.1.0
    - tokenizers==0.10.3
    - transformers==4.10.3

# Next: resolve conflict between sentence-transfomers and pytorch-lightning
# pip uninstall sentencepiece
